### PR TITLE
Move brick.py from desispec to desiutil

### PR DESCRIPTION
**Pull request by geordie666**
To deal with https://github.com/desihub/desispec/issues/310 without breaking unit tests we need to:

- merge this and tag it
- correct references to desispec.brick in desisim and desitarget, test and tag
- delete desispec.brick

### CODE REVIEW

**Comment by sbailey** [comment]
Please add a line in changes.rst, but otherwise fine to merge once travis tests finish running (and presumably pass).

**Comment by geordie666** [comment]
@sbailey, let me know when you've tagged desiutil and I'll move onto stage 2

**Comment by weaverba137** [comment]
Please delete the `movebrick` branch.  But in the future, could you at least give a teensy bit more time for other people to review?

**Comment by weaverba137** [comment]
PS, I fixed up a minor problem with changes.rst on master.  Be sure to update your master checkout before attempting to tag.

**Comment by sbailey** [comment]
I deleted the branch; let us know if you have any other retroactive requests and we can fix them up before the tag.  Thanks for the changes.rst update.

**Comment by weaverba137** [comment]
OK, go ahead & tag.

**Comment by weaverba137** [comment]
Belay that, I just found another documentation problem.

**Comment by geordie666** [comment]
You may have already found this, but it says:

""""

desispec.brick

==============

instead of desiututil.brick

At the top of brick.py.

Apologies...

**Comment by weaverba137** [comment]
That's one of the things I'm working on.

**Comment by moustakas** [comment]
I know this comment is coming a little late but why does the output of `desiutil.brick.Bricks` look like it does?  Can we have some functionality to turn the attributes in `Bricks.__init__` into something that looks like a flat, imaging-style "brick information" structure, with `ra`, `dec`, `ra1`, `ra2`, `dec1`, `dec2`, etc.?  

The code to do this is basically [here](https://github.com/desihub/desitarget/blob/sprintqa/py/desitarget/mock/build.py#L87-L136) so if someone has the cycles...

**Comment by weaverba137** [comment]
@moustakas, can you convert that into a separate issue?

**Comment by geordie666** [comment]
@weaverba137 beat me to it...for now let's merge this and tag it so that we can deal with the issue at hand before further editing the functionality. If we want different functionality in the future we can edit this in desiutil.

**Comment by sbailey** [comment]
@weaver please give the green light when you are ready to sign off on a tag (and go ahead and make the tag if you'd like...)

**Comment by weaverba137** [comment]
OK

**Comment by weaverba137** [comment]
Yes, I'll go ahead & tag momentarily.

**Comment by weaverba137** [comment]
Tag 1.9.4 is done!

**Pull request merged**
