### PR TITLE
Data census

### PR DESCRIPTION
**Pull request by weaverba137**
**Do not merge until I've had a chance to test this on WISE data!**

This PR creates a new command-line script `desi_data_census` that does accounting on the files stored in the DESI and cosmo repositories at NERSC.

To summarize it:

1. Scans a set of directories and subdirectories and counts the number of files (inodes) and bytes.
2. Handles cases where there are links back to another directory hierarchy and handles the accounting accordingly (for example if legacysurvey/dr3 contains a link to files in legacysurvey/dr2, the physical files count only toward legacysurvey/dr2).
3. Handles cases where there are links to another filesystem (*e.g.* project -> projecta).
4. Sorts the numbers and sizes by fiscal year.
5. Dumps the resulting low-level data into a YAML file.
6. Sorts and cumulative sums the data, and prints this to a CSV file.
7. The CSV file can then be ingested into a standard spreadsheet (Google Sheets or Excel).

### CODE REVIEW

**Comment by weaverba137** [comment]
With the directories listed in the current config.yaml file, it runs in 10-15 minutes, I think.  Much less than 1 hour, certainly.  That's looking at over 300 TB.

I did share a Google spreadsheet with you.  Did you look at that?  It did require bit of extra processing, that's true.  I just have a preference for fewer output files, I guess.

Hmm, GitHub doesn't let me drag & drop YAML files.  I'll try attaching them some other way.

**Comment by weaverba137** [comment]
Output YAML file.  This is used mainly for debugging.

```yaml
- !!python/object/apply:collections.OrderedDict
  dictitems:
    /global/project/projectdirs/cosmo/data/legacysurvey:
      2015:
        number: 909405
        size: 16517170260620
      2016:
        number: 5724024
        size: 99782150403719
      2017:
        number: 210815
        size: 247201166972
    /global/project/projectdirs/cosmo/data/legacysurvey/dr1:
      2015:
        number: 909405
        size: 16517170260620
    /global/project/projectdirs/cosmo/data/legacysurvey/dr2:
      2016:
        number: 2213532
        size: 36012502653457
    /global/project/projectdirs/cosmo/data/legacysurvey/dr3.0:
      2016:
        number: 3510490
        size: 63769647488118
      2017:
        number: 138631
        size: 9179162947
    /global/project/projectdirs/cosmo/data/legacysurvey/dr3.1:
      2017:
        number: 72180
        size: 238021610804
- !!python/object/apply:collections.OrderedDict
  dictitems:
    /global/project/projectdirs/cosmo/staging/decam:
      2014:
        number: 30715
        size: 6401491498942
      2015:
        number: 63648
        size: 13144762651991
      2016:
        number: 74102
        size: 18125317201014
      2017:
        number: 34257
        size: 10180985387575
    /global/project/projectdirs/cosmo/staging/decam/2013A-0741:
      2014:
        number: 54
        size: 9069662111
      2015:
        number: 1
        size: 4699
    /global/project/projectdirs/cosmo/staging/decam/COSMOS:
      2015:
        number: 759
        size: 1268072233988
    /global/project/projectdirs/cosmo/staging/decam/CPDES82:
      2015:
        number: 2179
        size: 348597006426
    /global/project/projectdirs/cosmo/staging/decam/DECam_CP:
      2014:
        number: 10732
        size: 1734343534080
      2015:
        number: 13640
        size: 2150149039212
      2016:
        number: 25028
        size: 5933350756793
      2017:
        number: 18428
        size: 4441122127414
    /global/project/projectdirs/cosmo/staging/decam/DECam_Raw:
      2014:
        number: 3040
        size: 1733443070400
      2015:
        number: 5118
        size: 2747873026864
      2016:
        number: 10947
        size: 5899278210232
      2017:
        number: 7159
        size: 3750007842728
    /global/project/projectdirs/cosmo/staging/decam/DESY1_Stripe82:
      2015:
        number: 3625
        size: 580225501128
    /global/project/projectdirs/cosmo/staging/decam/NonDECaLS:
      2014:
        number: 16536
        size: 2641978805760
      2015:
        number: 19639
        size: 3114723124463
      2016:
        number: 35089
        size: 5577821479749
    /global/project/projectdirs/cosmo/staging/decam/NonDECaLS-DR5:
      2014:
        number: 220
        size: 35582935680
      2015:
        number: 18685
        size: 2935122704640
      2016:
        number: 3038
        size: 714866754240
      2017:
        number: 8659
        size: 1989855136960
    /global/project/projectdirs/cosmo/staging/decam/Stacks_Aug14:
      2014:
        number: 132
        size: 23403974400
      2015:
        number: 1
        size: 10164
- !!python/object/apply:collections.OrderedDict
  dictitems:
    /global/project/projectdirs/cosmo/staging/mosaicz:
      2016:
        number: 29813
        size: 2043194648048
      2017:
        number: 118754
        size: 8617905610442
    /global/project/projectdirs/cosmo/staging/mosaicz/MZLS_CP:
      2017:
        number: 101209
        size: 4990111120254
    /global/project/projectdirs/cosmo/staging/mosaicz/MZLS_Raw:
      2016:
        number: 29813
        size: 2043194648048
      2017:
        number: 17542
        size: 3627794210184
- !!python/object/apply:collections.OrderedDict
  dictitems:
    /global/project/projectdirs/cosmo/staging/bok:
      2015:
        number: 11058
        size: 680068222315
      2016:
        number: 19207
        size: 1252489231113
      2017:
        number: 325041
        size: 16699300723086
    /global/project/projectdirs/cosmo/staging/bok/BOK_CP:
      2017:
        number: 37362
        size: 1861811097062
    /global/project/projectdirs/cosmo/staging/bok/BOK_Raw:
      2015:
        number: 11053
        size: 679318487432
      2016:
        number: 18947
        size: 1216303463528
      2017:
        number: 9729
        size: 1059122529240
    /global/project/projectdirs/cosmo/staging/bok/ccds_files:
      2016:
        number: 3
        size: 1912320
      2017:
        number: 1
        size: 13227840
    /global/project/projectdirs/cosmo/staging/bok/dr1d_naoc:
      2017:
        number: 139551
        size: 6924548934272
    /global/project/projectdirs/cosmo/staging/bok/engineering:
      2015:
        number: 5
        size: 749734883
      2016:
        number: 17
        size: 11623585272
    /global/project/projectdirs/cosmo/staging/bok/reduced:
      2016:
        number: 238
        size: 24560268944
      2017:
        number: 138392
        size: 6853804658944
- !!python/object/apply:collections.OrderedDict
  dictitems:
    /global/project/projectdirs/cosmo/staging/decam-public:
      2014:
        number: 18545
        size: 8987814440640
      2015:
        number: 158870
        size: 83924484778240
      2016:
        number: 121997
        size: 55435468307827
      2017:
        number: 3
        size: 21075006
```

**Comment by weaverba137** [comment]
CSV output.

```csv
Directory,FY2014 Number,FY2014 Size,FY2015 Number,FY2015 Size,FY2016 Number,FY2016 Size,FY2017 Number,FY2017 Size
/global/project/projectdirs/cosmo/data/legacysurvey,0,0,909405,16517170260620,6633429,116299320664339,6844244,116546521831311
/global/project/projectdirs/cosmo/data/legacysurvey/dr1,0,0,909405,16517170260620,909405,16517170260620,909405,16517170260620
/global/project/projectdirs/cosmo/data/legacysurvey/dr2,0,0,0,0,2213532,36012502653457,2213532,36012502653457
/global/project/projectdirs/cosmo/data/legacysurvey/dr3.0,0,0,0,0,3510490,63769647488118,3649121,63778826651065
/global/project/projectdirs/cosmo/data/legacysurvey/dr3.1,0,0,0,0,0,0,72180,238021610804
/global/project/projectdirs/cosmo/staging/decam,30715,6401491498942,94363,19546254150933,168465,37671571351947,202722,47852556739522
/global/project/projectdirs/cosmo/staging/decam/2013A-0741,54,9069662111,55,9069666810,55,9069666810,55,9069666810
/global/project/projectdirs/cosmo/staging/decam/COSMOS,0,0,759,1268072233988,759,1268072233988,759,1268072233988
/global/project/projectdirs/cosmo/staging/decam/CPDES82,0,0,2179,348597006426,2179,348597006426,2179,348597006426
/global/project/projectdirs/cosmo/staging/decam/DECam_CP,10732,1734343534080,24372,3884492573292,49400,9817843330085,67828,14258965457499
/global/project/projectdirs/cosmo/staging/decam/DECam_Raw,3040,1733443070400,8158,4481316097264,19105,10380594307496,26264,14130602150224
/global/project/projectdirs/cosmo/staging/decam/DESY1_Stripe82,0,0,3625,580225501128,3625,580225501128,3625,580225501128
/global/project/projectdirs/cosmo/staging/decam/NonDECaLS,16536,2641978805760,36175,5756701930223,71264,11334523409972,71264,11334523409972
/global/project/projectdirs/cosmo/staging/decam/NonDECaLS-DR5,220,35582935680,18905,2970705640320,21943,3685572394560,30602,5675427531520
/global/project/projectdirs/cosmo/staging/decam/Stacks_Aug14,132,23403974400,133,23403984564,133,23403984564,133,23403984564
/global/project/projectdirs/cosmo/staging/mosaicz,0,0,0,0,29813,2043194648048,148567,10661100258490
/global/project/projectdirs/cosmo/staging/mosaicz/MZLS_CP,0,0,0,0,0,0,101209,4990111120254
/global/project/projectdirs/cosmo/staging/mosaicz/MZLS_Raw,0,0,0,0,29813,2043194648048,47355,5670988858232
/global/project/projectdirs/cosmo/staging/bok,0,0,11058,680068222315,30265,1932557453428,355306,18631858176514
/global/project/projectdirs/cosmo/staging/bok/BOK_CP,0,0,0,0,0,0,37362,1861811097062
/global/project/projectdirs/cosmo/staging/bok/BOK_Raw,0,0,11053,679318487432,30000,1895621950960,39729,2954744480200
/global/project/projectdirs/cosmo/staging/bok/ccds_files,0,0,0,0,3,1912320,4,15140160
/global/project/projectdirs/cosmo/staging/bok/dr1d_naoc,0,0,0,0,0,0,139551,6924548934272
/global/project/projectdirs/cosmo/staging/bok/engineering,0,0,5,749734883,22,12373320155,22,12373320155
/global/project/projectdirs/cosmo/staging/bok/reduced,0,0,0,0,238,24560268944,138630,6878364927888
/global/project/projectdirs/cosmo/staging/decam-public,18545,8987814440640,177415,92912299218880,299412,148347767526707,299415,148347788601713
```

**Comment by weaverba137** [comment]
PS, one item I forgot to mention: this code will also identify files that do not have the correct group id for the directory hierarchy they are in.

**Comment by sbailey** [comment]
yes, I saw the google sheet, which prompted the thought about CSV column order.

A single csv output file is fine, just consider ordering the columns as
```
Directory,FY2014 Number,FY2015 Number, ... FY2014 Size, FY2015 Size, ...
```
Instead of
```
Directory,FY2014 Number,FY2014 Size,FY2015 Number,FY2015 Size,...
```

I think that would make the spreadsheet easier to work with in the end.

**Comment by weaverba137** [comment]
Ah, OK, that's easy.

**Comment by weaverba137** [comment]
I've added WISE directories and will merge this once it has run successfully on those directories.

**Pull request merged**
